
[Discord]

  # Discord Channel to sent screenshots to leave blank to use built in server
  ChannelID = ""

  # Discord Bot Token leave blank to use built in server
  Token = ""

[Everquest]

  # Path to screenshot folder leave blank to auto detect
  ScreenshotPath = "C:\\Program Files (x86)\\Steam\\steamapps\\common\\Everquest F2P\\Screenshots"

[Log]

  # Where to store logs leave blank to use EQscreenshotUploader.log
  Path = "EQscreenshotUploader.log"

[Main]

  # Amount of blur to apply to partial screenshots. Defaults to 6.5
  BlurAmount = 6.5

  # Blur partial screenshots. Defaults to false
  BlurPartial = true

  # X end coordinate of box to blur
  BlurXEnd = 2559

  # X start coordinate of box to blur
  BlurXStart = 0

  # y end coordinate of box to blur
  BlurYEnd = 1398

  # y start coordinate of box to blur
  BlurYStart = 1042

  # Extension for screenshots defaults to .jpg
  ScreenshotExtension = ".jpg"

  # Time to wait (in seconds) to upload the screenshot. We have to delay until it's finished writing and released for reading defaults to 5 seconds
  UploadDelay = 5
